---
- hosts: all #group name from the inventory
  user: ec2-user
  sudo: true

  tasks: 
    - name: create user
      user: name={{item}} state=present
      with_items:
        - user1
        - user2
        - user2 
...
