---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-5b673c34  # Redhat
      keypair: devops # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "AKIAIBZOEDJ5ZPLIZWGQ"
         aws_secret_key: "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"
         group: SG1  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Demo"
         instance_tags:
            Name: "Demo"
         vpc_subnet_id: "subnet-78652f10"
         assign_public_ip: yes
      register: ec2
