---
- hosts: all #group name from the inventory
  user: ec2-user
  sudo: true

  vars_files:
    - common_list.yml
  tasks:
    - name: install pakgs
      yum: name={{ item }} state=installed
      loop: "{{ listofpackages }}"
...
